# Generated by Django 2.2 on 2020-10-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='desc',
            field=models.TextField(default='This Course'),
        ),
        migrations.DeleteModel(
            name='Desc',
        ),
    ]
